/* AUTO-GENERATED — mirrors the real `api.getIndex()` shape for Components + Icons. */
/* Storybook IDs follow @storybook/csf `sanitize` (lowercase + special chars → dash). */
import type { StoryIndex } from './build-sidebar';

export const SAMPLE_INDEX: StoryIndex = {
  entries: {
    'components-badges-badgegroup--docs': { id: 'components-badges-badgegroup--docs', title: 'Components/Badges/BadgeGroup', name: "Docs", type: 'docs' },
    'components-badges-badgegroup--playground': { id: 'components-badges-badgegroup--playground', title: 'Components/Badges/BadgeGroup', name: "Playground", type: 'story' },
    'components-badges-badgegroup--digits-2': { id: 'components-badges-badgegroup--digits-2', title: 'Components/Badges/BadgeGroup', name: "digits=2", type: 'story' },
    'components-badges-badgegroup--digits-3': { id: 'components-badges-badgegroup--digits-3', title: 'Components/Badges/BadgeGroup', name: "digits=3", type: 'story' },
    'components-badges-badgegroup--all-variants': { id: 'components-badges-badgegroup--all-variants', title: 'Components/Badges/BadgeGroup', name: "All variants", type: 'story' },
    'components-badges-digits--docs': { id: 'components-badges-digits--docs', title: 'Components/Badges/Digits', name: "Docs", type: 'docs' },
    'components-badges-digits--playground': { id: 'components-badges-digits--playground', title: 'Components/Badges/Digits', name: "Playground", type: 'story' },
    'components-badges-digits--outlined-1-2-chars': { id: 'components-badges-digits--outlined-1-2-chars', title: 'Components/Badges/Digits', name: "Outlined / 1-2 chars", type: 'story' },
    'components-badges-digits--outlined-3-chars': { id: 'components-badges-digits--outlined-3-chars', title: 'Components/Badges/Digits', name: "Outlined / 3 chars", type: 'story' },
    'components-badges-digits--outlined-constant-inverted-1-2-chars': { id: 'components-badges-digits--outlined-constant-inverted-1-2-chars', title: 'Components/Badges/Digits', name: "Outlined constant inverted / 1-2 chars", type: 'story' },
    'components-badges-digits--outlined-constant-inverted-3-chars': { id: 'components-badges-digits--outlined-constant-inverted-3-chars', title: 'Components/Badges/Digits', name: "Outlined constant inverted / 3 chars", type: 'story' },
    'components-badges-digits--tonned-1-2-chars': { id: 'components-badges-digits--tonned-1-2-chars', title: 'Components/Badges/Digits', name: "Tonned / 1-2 chars", type: 'story' },
    'components-badges-digits--tonned-3-chars': { id: 'components-badges-digits--tonned-3-chars', title: 'Components/Badges/Digits', name: "Tonned / 3 chars", type: 'story' },
    'components-badges-digits--all-variants': { id: 'components-badges-digits--all-variants', title: 'Components/Badges/Digits', name: "All variants", type: 'story' },
    'components-badges-text--docs': { id: 'components-badges-text--docs', title: 'Components/Badges/Text', name: "Docs", type: 'docs' },
    'components-badges-text--playground': { id: 'components-badges-text--playground', title: 'Components/Badges/Text', name: "Playground", type: 'story' },
    'components-badges-text--filled': { id: 'components-badges-text--filled', title: 'Components/Badges/Text', name: "Filled", type: 'story' },
    'components-badges-text--filled-with-icon': { id: 'components-badges-text--filled-with-icon', title: 'Components/Badges/Text', name: "Filled / with icon", type: 'story' },
    'components-badges-text--outlined': { id: 'components-badges-text--outlined', title: 'Components/Badges/Text', name: "Outlined", type: 'story' },
    'components-badges-text--outlined-with-icon': { id: 'components-badges-text--outlined-with-icon', title: 'Components/Badges/Text', name: "Outlined / with icon", type: 'story' },
    'components-badges-text--brand': { id: 'components-badges-text--brand', title: 'Components/Badges/Text', name: "Brand", type: 'story' },
    'components-badges-text--brand-with-icon': { id: 'components-badges-text--brand-with-icon', title: 'Components/Badges/Text', name: "Brand / with icon", type: 'story' },
    'components-badges-text--tonned': { id: 'components-badges-text--tonned', title: 'Components/Badges/Text', name: "Tonned", type: 'story' },
    'components-badges-text--tonned-with-icon': { id: 'components-badges-text--tonned-with-icon', title: 'Components/Badges/Text', name: "Tonned / with icon", type: 'story' },
    'components-badges-text--all-variants': { id: 'components-badges-text--all-variants', title: 'Components/Badges/Text', name: "All variants", type: 'story' },
    'icons-icon--docs': { id: 'icons-icon--docs', title: 'Icons/Icon', name: "Docs", type: 'docs' },
    'icons-icon--all-20px': { id: 'icons-icon--all-20px', title: 'Icons/Icon', name: "All / 20px", type: 'story' },
    'icons-icon--all-28px': { id: 'icons-icon--all-28px', title: 'Icons/Icon', name: "All / 28px", type: 'story' },
    'components-tabs-tab-feature-digit--docs': { id: 'components-tabs-tab-feature-digit--docs', title: 'Components/Tabs/Tab Feature Digit', name: "Docs", type: 'docs' },
    'components-tabs-tab-feature-digit--playground': { id: 'components-tabs-tab-feature-digit--playground', title: 'Components/Tabs/Tab Feature Digit', name: "Playground", type: 'story' },
    'components-tabs-tab-feature-digit--all-variants': { id: 'components-tabs-tab-feature-digit--all-variants', title: 'Components/Tabs/Tab Feature Digit', name: "All variants", type: 'story' },
    'components-tabs-tab-item--docs': { id: 'components-tabs-tab-item--docs', title: 'Components/Tabs/Tab Item', name: "Docs", type: 'docs' },
    'components-tabs-tab-item--playground': { id: 'components-tabs-tab-item--playground', title: 'Components/Tabs/Tab Item', name: "Playground", type: 'story' },
    'components-tabs-tab-item--all-variants': { id: 'components-tabs-tab-item--all-variants', title: 'Components/Tabs/Tab Item', name: "All variants", type: 'story' },
    'components-tabs-tabs-group-column--docs': { id: 'components-tabs-tabs-group-column--docs', title: 'Components/Tabs/Tabs Group Column', name: "Docs", type: 'docs' },
    'components-tabs-tabs-group-column--playground': { id: 'components-tabs-tabs-group-column--playground', title: 'Components/Tabs/Tabs Group Column', name: "Playground", type: 'story' },
    'components-tabs-tabs-group-column--all-variants': { id: 'components-tabs-tabs-group-column--all-variants', title: 'Components/Tabs/Tabs Group Column', name: "All variants", type: 'story' },
    'components-tabs-tabs-group-row--docs': { id: 'components-tabs-tabs-group-row--docs', title: 'Components/Tabs/Tabs Group Row', name: "Docs", type: 'docs' },
    'components-tabs-tabs-group-row--playground': { id: 'components-tabs-tabs-group-row--playground', title: 'Components/Tabs/Tabs Group Row', name: "Playground", type: 'story' },
    'components-tabs-tabs-group-row--all-variants': { id: 'components-tabs-tabs-group-row--all-variants', title: 'Components/Tabs/Tabs Group Row', name: "All variants", type: 'story' },
    'components-tags-tag--docs': { id: 'components-tags-tag--docs', title: 'Components/Tags/Tag', name: "Docs", type: 'docs' },
    'components-tags-tag--playground': { id: 'components-tags-tag--playground', title: 'Components/Tags/Tag', name: "Playground", type: 'story' },
    'components-tags-tag--all-variants': { id: 'components-tags-tag--all-variants', title: 'Components/Tags/Tag', name: "All variants", type: 'story' },
    'components-tags-taggroup--docs': { id: 'components-tags-taggroup--docs', title: 'Components/Tags/TagGroup', name: "Docs", type: 'docs' },
    'components-tags-taggroup--playground': { id: 'components-tags-taggroup--playground', title: 'Components/Tags/TagGroup', name: "Playground", type: 'story' },
    'components-tags-taggroup--all-variants': { id: 'components-tags-taggroup--all-variants', title: 'Components/Tags/TagGroup', name: "All variants", type: 'story' },
    'components-buttons-button-icon-only--docs': { id: 'components-buttons-button-icon-only--docs', title: 'Components/Buttons/Button Icon Only', name: "Docs", type: 'docs' },
    'components-buttons-button-icon-only--playground': { id: 'components-buttons-button-icon-only--playground', title: 'Components/Buttons/Button Icon Only', name: "Playground", type: 'story' },
    'components-buttons-button-icon-only--all-variants': { id: 'components-buttons-button-icon-only--all-variants', title: 'Components/Buttons/Button Icon Only', name: "All variants", type: 'story' },
    'components-buttons-button-social--docs': { id: 'components-buttons-button-social--docs', title: 'Components/Buttons/Button Social', name: "Docs", type: 'docs' },
    'components-buttons-button-social--playground': { id: 'components-buttons-button-social--playground', title: 'Components/Buttons/Button Social', name: "Playground", type: 'story' },
    'components-buttons-button-social--all-variants': { id: 'components-buttons-button-social--all-variants', title: 'Components/Buttons/Button Social', name: "All variants", type: 'story' },
    'components-buttons-button-text--docs': { id: 'components-buttons-button-text--docs', title: 'Components/Buttons/Button Text', name: "Docs", type: 'docs' },
    'components-buttons-button-text--playground': { id: 'components-buttons-button-text--playground', title: 'Components/Buttons/Button Text', name: "Playground", type: 'story' },
    'components-buttons-button-text--all-variants': { id: 'components-buttons-button-text--all-variants', title: 'Components/Buttons/Button Text', name: "All variants", type: 'story' },
    'components-buttons-button-text-icon--docs': { id: 'components-buttons-button-text-icon--docs', title: 'Components/Buttons/Button Text Icon', name: "Docs", type: 'docs' },
    'components-buttons-button-text-icon--playground': { id: 'components-buttons-button-text-icon--playground', title: 'Components/Buttons/Button Text Icon', name: "Playground", type: 'story' },
    'components-buttons-button-text-icon--all-variants': { id: 'components-buttons-button-text-icon--all-variants', title: 'Components/Buttons/Button Text Icon', name: "All variants", type: 'story' },
    'components-buttons-button-text-only--docs': { id: 'components-buttons-button-text-only--docs', title: 'Components/Buttons/Button Text Only', name: "Docs", type: 'docs' },
    'components-buttons-button-text-only--playground': { id: 'components-buttons-button-text-only--playground', title: 'Components/Buttons/Button Text Only', name: "Playground", type: 'story' },
    'components-buttons-button-text-only--all-variants': { id: 'components-buttons-button-text-only--all-variants', title: 'Components/Buttons/Button Text Only', name: "All variants", type: 'story' },
    'components-checkboxes-checkboxitem--docs': { id: 'components-checkboxes-checkboxitem--docs', title: 'Components/Checkboxes/CheckboxItem', name: "Docs", type: 'docs' },
    'components-checkboxes-checkboxitem--playground': { id: 'components-checkboxes-checkboxitem--playground', title: 'Components/Checkboxes/CheckboxItem', name: "Playground", type: 'story' },
    'components-checkboxes-checkboxitem--unchecked': { id: 'components-checkboxes-checkboxitem--unchecked', title: 'Components/Checkboxes/CheckboxItem', name: "Unchecked", type: 'story' },
    'components-checkboxes-checkboxitem--checked': { id: 'components-checkboxes-checkboxitem--checked', title: 'Components/Checkboxes/CheckboxItem', name: "Checked", type: 'story' },
    'components-checkboxes-checkboxitem--disabled-unchecked': { id: 'components-checkboxes-checkboxitem--disabled-unchecked', title: 'Components/Checkboxes/CheckboxItem', name: "Disabled / unchecked", type: 'story' },
    'components-checkboxes-checkboxitem--disabled-checked': { id: 'components-checkboxes-checkboxitem--disabled-checked', title: 'Components/Checkboxes/CheckboxItem', name: "Disabled / checked", type: 'story' },
    'components-checkboxes-checkboxitem--all-variants': { id: 'components-checkboxes-checkboxitem--all-variants', title: 'Components/Checkboxes/CheckboxItem', name: "All variants", type: 'story' },
    'components-checkboxes-checkboxitem--interactive-hover-click': { id: 'components-checkboxes-checkboxitem--interactive-hover-click', title: 'Components/Checkboxes/CheckboxItem', name: "Interactive (hover / click)", type: 'story' },
    'components-checkboxes-checkboxtoggle--docs': { id: 'components-checkboxes-checkboxtoggle--docs', title: 'Components/Checkboxes/CheckboxToggle', name: "Docs", type: 'docs' },
    'components-checkboxes-checkboxtoggle--playground': { id: 'components-checkboxes-checkboxtoggle--playground', title: 'Components/Checkboxes/CheckboxToggle', name: "Playground", type: 'story' },
    'components-checkboxes-checkboxtoggle--off-normal': { id: 'components-checkboxes-checkboxtoggle--off-normal', title: 'Components/Checkboxes/CheckboxToggle', name: "Off / normal", type: 'story' },
    'components-checkboxes-checkboxtoggle--on-normal': { id: 'components-checkboxes-checkboxtoggle--on-normal', title: 'Components/Checkboxes/CheckboxToggle', name: "On / normal", type: 'story' },
    'components-checkboxes-checkboxtoggle--off-hover': { id: 'components-checkboxes-checkboxtoggle--off-hover', title: 'Components/Checkboxes/CheckboxToggle', name: "Off / hover", type: 'story' },
    'components-checkboxes-checkboxtoggle--on-hover': { id: 'components-checkboxes-checkboxtoggle--on-hover', title: 'Components/Checkboxes/CheckboxToggle', name: "On / hover", type: 'story' },
    'components-checkboxes-checkboxtoggle--off-click': { id: 'components-checkboxes-checkboxtoggle--off-click', title: 'Components/Checkboxes/CheckboxToggle', name: "Off / click", type: 'story' },
    'components-checkboxes-checkboxtoggle--on-click': { id: 'components-checkboxes-checkboxtoggle--on-click', title: 'Components/Checkboxes/CheckboxToggle', name: "On / click", type: 'story' },
    'components-checkboxes-checkboxtoggle--off-disabled': { id: 'components-checkboxes-checkboxtoggle--off-disabled', title: 'Components/Checkboxes/CheckboxToggle', name: "Off / disabled", type: 'story' },
    'components-checkboxes-checkboxtoggle--on-disabled': { id: 'components-checkboxes-checkboxtoggle--on-disabled', title: 'Components/Checkboxes/CheckboxToggle', name: "On / disabled", type: 'story' },
    'components-checkboxes-checkboxtoggle--all-variants': { id: 'components-checkboxes-checkboxtoggle--all-variants', title: 'Components/Checkboxes/CheckboxToggle', name: "All variants", type: 'story' },
    'components-checkboxes-checkboxtoggle--interactive-hover-click': { id: 'components-checkboxes-checkboxtoggle--interactive-hover-click', title: 'Components/Checkboxes/CheckboxToggle', name: "Interactive (hover / click)", type: 'story' },
    'components-input-inputoutlined--docs': { id: 'components-input-inputoutlined--docs', title: 'Components/Input/InputOutlined', name: "Docs", type: 'docs' },
    'components-input-inputoutlined--playground': { id: 'components-input-inputoutlined--playground', title: 'Components/Input/InputOutlined', name: "Playground", type: 'story' },
    'components-input-inputoutlined--all-variants': { id: 'components-input-inputoutlined--all-variants', title: 'Components/Input/InputOutlined', name: "All variants", type: 'story' },
  },
};
