export { SectionHeadline, type SectionHeadlineProps } from './SectionHeadline';
export {
  HEADLINES_FIGMA_NODE_ID,
  HEADLINES_SLOT_SECTION_HEADLINE,
  SECTION_HEADLINE_DEFAULT_BUTTON_TEXT,
  SECTION_HEADLINE_DEFAULT_HEADLINE_TEXT,
  SECTION_HEADLINE_FIGMA_NODE_ID,
  SECTION_HEADLINE_VARIANTS,
} from './types';
